version: "3.4"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/media/plex/:/config
      - /mnt/media/shows:/shows
      - /mnt/media/movies:/movies
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EAmerica/Toronto
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/media/radarr/:/config
      - /mnt/media/movies:/movies
      - /mnt/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /mnt/media/sonarr/:/config
      - /mnt/media/shows:/shows
      - /mnt/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  # deluge:
  #   image: ghcr.io/linuxserver/deluge
  #   container_name: deluge
  #   network_mode: host
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=EAmerica/Toronto
  #     - UMASK_SET=022 #optional
  #     - DELUGE_LOGLEVEL=error #optional
  #   volumes:
  #     - /media/deluge/:/config
  #     - /media/downloads:/downloads
  #   restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EAmerica/Toronto
      - USER=transmission #optional
      - PASS=transmission #optional
    volumes:
      - /mnt/media/transmission:/config
      - /mnt/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EAmerica/Toronto
      - AUTO_UPDATE=true #optional
    volumes:
      - /mnt/media/jackett/:/config
      - /mnt/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EAmerica/Toronto
    volumes:
      - /mnt/media/organizr/:/config
    ports:
      - 4444:80
    restart: unless-stopped

  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EAmerica/Toronto
    volumes:
      - /mnt/media/ddclient/:/config
    restart: unless-stopped 