version: "3.4"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - UMASK=022 #optional
    volumes:
      - ./config/plex:/config
      - tnas-shows:/shows
      - tnas-movies:/movies
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=EAmerica/Toronto
      - UMASK=022 #optional
    volumes:
      - ./config/radarr:/config
      - tnas-movies:/movies
      - tnas-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - UMASK=022 #optional
    volumes:
      - ./config/sonarr:/config
      - tnas-shows:/shows
      - tnas-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=EAmerica/Toronto
      - USER=transmission #optional
      - PASS=transmission #optional
    volumes:
      - ./config/transmission:/config
      - tnas-downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=EAmerica/Toronto
      - AUTO_UPDATE=true #optional
    volumes:
      - ./config/jackett:/config
      - tnas-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=EAmerica/Toronto
    volumes:
      - ./config/organizr:/config
    ports:
      - 4444:80
    restart: unless-stopped

  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=EAmerica/Toronto
    volumes:
      - ./config/ddclient:/config
    restart: unless-stopped

volumes:

  tnas-downloads:
    driver_opts:
      type: cifs
      o: "username=username,password=password,uid=1001,gid=1001,rw"
      device: "//192.168.X.XXX/downloads"

  tnas-shows:
    driver_opts:
      type: cifs
      o: "username=username,password=password,uid=1001,gid=1001,rw"
      device: "//192.168.X.XXX/media/shows"

  tnas-movies:
    driver_opts:
      type: cifs
      o: "username=username,password=password,uid=1001,gid=1001,rw"
      device: "//192.168.X.XXX/media/movies"